/**
 * Mazo privado transcrito a partir de tarjetas físicas aportadas por el dueño
 * del proyecto. No se publica ni se reutiliza fuera de este MVP familiar.
 */
export type CardCategory = 'sequence' | 'association' | 'common' | 'approximation'

export type SequenceCard = {
  category: 'sequence'
  id: string
  instruction: string
  items: string[]
  correctOrder: string[]
}

export type AssociationCard = {
  category: 'association'
  id: string
  instruction: string
  leftItems: string[]
  rightItems: string[]
  pairs: Array<{ left: string; right: string }>
}

export type CommonCard = {
  category: 'common'
  id: string
  clues: string[]
  solution: string
}

export type ApproximationCard = {
  category: 'approximation'
  id: string
  prompt: string
  solution: { display: string; unit: string; value: number }
}

export type QuestionCard = SequenceCard | AssociationCard | CommonCard | ApproximationCard

const additionalSequenceCards: SequenceCard[] = [
  ['Planetas por distancia al Sol', ['Marte','Venus','Júpiter','Mercurio','Tierra'], ['Mercurio','Venus','Tierra','Marte','Júpiter']],
  ['Planetas por diámetro ecuatorial', ['Marte','Venus','Mercurio','Tierra','Neptuno'], ['Mercurio','Marte','Venus','Tierra','Neptuno']],
  ['Elementos por número atómico', ['Carbono','Helio','Oxígeno','Hidrógeno','Nitrógeno'], ['Hidrógeno','Helio','Carbono','Nitrógeno','Oxígeno']],
  ['Prefijos SI de menor a mayor', ['kilo','micro','mega','mili','giga'], ['micro','mili','kilo','mega','giga']],
  ['Misiones Gemini cronológicamente', ['Gemini 12','Gemini 3','Gemini 8','Gemini 4','Gemini 10'], ['Gemini 3','Gemini 4','Gemini 8','Gemini 10','Gemini 12']],
  ['Números romanos de menor a mayor', ['XC','IX','XL','V','L'], ['V','IX','XL','L','XC']],
  ['Unidades de masa de menor a mayor', ['kilogramo','tonelada','gramo','miligramo','microgramo'], ['microgramo','miligramo','gramo','kilogramo','tonelada']],
  ['Parques nacionales argentinos por creación', ['Los Glaciares','Nahuel Huapi','El Palmar','Iguazú','Talampaya'], ['Nahuel Huapi','Iguazú','El Palmar','Los Glaciares','Talampaya']],
  ['Montañas argentinas de menor a mayor altura', ['Lanín','Aconcagua','Fitz Roy','Tronador','Champaquí'], ['Champaquí','Fitz Roy','Tronador','Lanín','Aconcagua']],
  ['Patrimonios argentinos por inscripción UNESCO', ['Cueva de las Manos','Quebrada de Humahuaca','Qhapaq Ñan','Misiones Jesuíticas','Los Glaciares'], ['Los Glaciares','Misiones Jesuíticas','Cueva de las Manos','Quebrada de Humahuaca','Qhapaq Ñan']],
  ['Países sudamericanos por superficie', ['Chile','Brasil','Uruguay','Bolivia','Ecuador'], ['Uruguay','Ecuador','Chile','Bolivia','Brasil']],
  ['Independencias cronológicamente', ['Argentina','Estados Unidos','Brasil','India','México'], ['Estados Unidos','Argentina','México','Brasil','India']],
  ['Océanos por superficie', ['Índico','Ártico','Pacífico','Atlántico','Austral'], ['Ártico','Austral','Índico','Atlántico','Pacífico']],
  ['Lagos por profundidad máxima', ['Victoria','Baikal','Superior','Titicaca','Tanganica'], ['Victoria','Superior','Titicaca','Tanganica','Baikal']],
  ['Libros de Julio Verne por publicación', ['La vuelta al mundo en 80 días','Viaje al centro de la Tierra','Miguel Strogoff','Veinte mil leguas de viaje submarino','De la Tierra a la Luna'], ['Viaje al centro de la Tierra','De la Tierra a la Luna','Veinte mil leguas de viaje submarino','La vuelta al mundo en 80 días','Miguel Strogoff']],
  ['Harry Potter por publicación', ['El prisionero de Azkaban','La piedra filosofal','El cáliz de fuego','La cámara secreta','La Orden del Fénix'], ['La piedra filosofal','La cámara secreta','El prisionero de Azkaban','El cáliz de fuego','La Orden del Fénix']],
  ['Monedas estadounidenses por valor', ['nickel','quarter','penny','half dollar','dime'], ['penny','nickel','dime','quarter','half dollar']],
  ['Productos Apple por lanzamiento', ['Macintosh','iMac','Apple II','iPhone','iPad'], ['Apple II','Macintosh','iMac','iPhone','iPad']],
  ['Mundiales de fútbol cronológicamente', ['Alemania 2006','México 1986','Sudáfrica 2010','Francia 1998','Corea-Japón 2002'], ['México 1986','Francia 1998','Corea-Japón 2002','Alemania 2006','Sudáfrica 2010']],
  ['Meses por días en año no bisiesto', ['febrero','abril','julio','septiembre','noviembre'], ['febrero','abril','septiembre','noviembre','julio']],
  ['Edades geológicas de más reciente a más antigua', ['Jurásico','Cretácico','Triásico','Cuaternario','Paleógeno'], ['Cuaternario','Paleógeno','Cretácico','Jurásico','Triásico']],
  ['Carreras por distancia', ['5K','media maratón','maratón','10K','milla'], ['milla','5K','10K','media maratón','maratón']],
  ['Presidentes argentinos por primera asunción', ['Raúl Alfonsín','Arturo Illia','Néstor Kirchner','Hipólito Yrigoyen','Juan D. Perón'], ['Hipólito Yrigoyen','Juan D. Perón','Arturo Illia','Raúl Alfonsín','Néstor Kirchner']],
  ['Planetas por duración de su año', ['Júpiter','Venus','Marte','Mercurio','Tierra'], ['Mercurio','Venus','Tierra','Marte','Júpiter']],
  ['Diarios argentinos por fundación', ['La Nación','Página/12','Clarín','La Prensa','Perfil'], ['La Prensa','La Nación','Clarín','Página/12','Perfil']],
  ['Deportes por jugadores por equipo', ['vóley','básquet','fútbol','handball','hockey sobre césped'], ['básquet','vóley','handball','hockey sobre césped','fútbol']],
  ['Películas de Pixar por estreno', ['Toy Story','Buscando a Nemo','Monsters, Inc.','Los Increíbles','WALL·E'], ['Toy Story','Monsters, Inc.','Buscando a Nemo','Los Increíbles','WALL·E']],
  ['Lunas de Júpiter por distancia al planeta', ['Calisto','Europa','Ío','Ganímedes','Amaltea'], ['Amaltea','Ío','Europa','Ganímedes','Calisto']],
  ['Hitos espaciales cronológicamente', ['Apollo 11','Sputnik 1','Voyager 1','Curiosity en Marte','Hubble'], ['Sputnik 1','Apollo 11','Voyager 1','Hubble','Curiosity en Marte']],
  ['Patrimonios del Perú por inscripción UNESCO', ['Chan Chan','Chankillo','Machu Picchu','Caral-Supe','Líneas de Nazca'], ['Machu Picchu','Chan Chan','Líneas de Nazca','Caral-Supe','Chankillo']],
].map(([instruction, items, correctOrder], index) => ({ category: 'sequence', id: `sequence-original-${index + 1}`, instruction: `Ordene ${instruction}:`, items, correctOrder })) as SequenceCard[]

const additionalAssociationCards: AssociationCard[] = [
  ['elemento con símbolo', ['Sodio','Potasio','Plata','Oro','Hierro'], ['Na','K','Ag','Au','Fe']],
  ['elemento con número atómico', ['Hidrógeno','Carbono','Oxígeno','Sodio','Oro'], ['1','6','8','11','79']],
  ['unidad SI con símbolo', ['segundo','kelvin','amperio','mol','candela'], ['s','K','A','mol','cd']],
  ['país con capital', ['Canadá','Australia','Brasil','Turquía','Suiza'], ['Ottawa','Canberra','Brasilia','Ankara','Berna']],
  ['país sudamericano con capital', ['Bolivia','Ecuador','Paraguay','Perú','Uruguay'], ['Sucre','Quito','Asunción','Lima','Montevideo']],
  ['provincia argentina con capital', ['Jujuy','Misiones','Neuquén','Río Negro','Tierra del Fuego'], ['San Salvador de Jujuy','Posadas','Neuquén','Viedma','Ushuaia']],
  ['sitio argentino UNESCO con año de inscripción', ['Cueva de las Manos','Quebrada de Humahuaca','Misiones Jesuíticas','Los Glaciares','Parque Nacional Iguazú'], ['1999','2003','1983','1981','1984']],
  ['monumento con ciudad', ['Torre Eiffel','Coliseo','Estatua de la Libertad','Cristo Redentor','Ópera de Sídney'], ['París','Roma','Nueva York','Río de Janeiro','Sídney']],
  ['río con ciudad', ['Támesis','Danubio','Sena','Tíber','Nilo'], ['Londres','Budapest','París','Roma','El Cairo']],
  ['cordillera con continente', ['Andes','Alpes','Himalaya','Atlas','Gran Cordillera Divisoria'], ['América del Sur','Europa','Asia','África','Oceanía']],
  ['parque argentino con rasgo', ['Iguazú','Los Glaciares','El Palmar','Talampaya','Nahuel Huapi'], ['cataratas','glaciares','palmares','cañón','lagos y bosque andino']],
  ['misión espacial con agencia', ['Apollo','Rosetta','Chandrayaan','Hayabusa','Tianwen'], ['NASA','ESA','ISRO','JAXA','CNSA']],
  ['planeta con rasgo', ['Mercurio','Venus','Tierra','Marte','Júpiter'], ['más cercano al Sol','más caliente','agua líquida superficial','Olympus Mons','más grande']],
  ['invento con inventor', ['teléfono','radio','dinamita','imprenta de tipos móviles','penicilina'], ['Alexander Graham Bell','Guglielmo Marconi','Alfred Nobel','Johannes Gutenberg','Alexander Fleming']],
  ['obra con autor/a', ['Frankenstein','Don Quijote','Cien años de soledad','Ficciones','Orgullo y prejuicio'], ['Mary Shelley','Miguel de Cervantes','Gabriel García Márquez','Jorge Luis Borges','Jane Austen']],
  ['obra musical con compositor', ['Las cuatro estaciones','La flauta mágica','El lago de los cisnes','Carmen','Bolero'], ['Vivaldi','Mozart','Chaikovski','Bizet','Ravel']],
  ['pintor con obra', ['Guernica','La noche estrellada','Las meninas','El grito','La persistencia de la memoria'], ['Picasso','Van Gogh','Velázquez','Munch','Dalí']],
  ['científico con aporte', ['Newton','Darwin','Curie','Mendel','Pasteur'], ['leyes del movimiento','selección natural','radioactividad','herencia','pasteurización']],
  ['órgano con sistema', ['corazón','pulmón','riñón','estómago','cerebro'], ['circulatorio','respiratorio','urinario','digestivo','nervioso']],
  ['capa terrestre con descripción', ['corteza','manto','núcleo externo','núcleo interno','atmósfera'], ['capa externa sólida','roca bajo la corteza','metal líquido','metal sólido','envoltura gaseosa']],
  ['moneda con país', ['yen','won','rupia','corona','peso'], ['Japón','Corea del Sur','India','Suecia','Argentina']],
  ['organismo ONU con sede', ['UNESCO','FAO','OACI','OIT','OMI'], ['París','Roma','Montreal','Ginebra','Londres']],
  ['deporte con jugadores por equipo', ['básquet','vóley','handball','béisbol','fútbol'], ['5','6','7','9','11']],
  ['animal con clase', ['ballena','rana','águila','tiburón','iguana'], ['mamífero','anfibio','ave','pez','reptil']],
  ['satélite con planeta', ['Luna','Fobos','Europa','Titán','Tritón'], ['Tierra','Marte','Júpiter','Saturno','Neptuno']],
  ['prefijo SI con factor', ['kilo','mega','giga','mili','micro'], ['10³','10⁶','10⁹','10⁻³','10⁻⁶']],
  ['cuerpo del Sistema Solar con rasgo', ['Ío','Europa','Ganímedes','Calisto','Titán'], ['actividad volcánica','océano bajo hielo','la mayor luna','muchos cráteres','luna de Saturno']],
  ['cuerpo del Sistema Solar con rasgo', ['Fobos','Deimos','Mercurio','Venus','Marte'], ['mayor e interior','menor y exterior','planeta más cercano','planeta más caliente','planeta rojo']],
  ['sitio UNESCO con país', ['Machu Picchu','Teotihuacan','Angkor','Petra','Serengeti'], ['Perú','México','Camboya','Jordania','Tanzania']],
  ['planeta con satélite', ['Tierra','Marte','Júpiter','Saturno','Neptuno'], ['Luna','Fobos','Europa','Titán','Tritón']],
].map((entry, index) => {
  const [instruction, leftItems, rightItems] = entry as [string, string[], string[]]
  return { category: 'association', id: `association-original-${index + 1}`, instruction: `Asocie ${instruction}:`, leftItems, rightItems, pairs: leftItems.map((left, i) => ({ left, right: rightItems[i] })) }
}) as AssociationCard[]

const additionalCommonCards: CommonCard[] = [
  [['Mercurio', 'Venus', 'Tierra', 'Marte', 'Júpiter'], 'Son planetas del Sistema Solar.'],
  [['Fobos', 'Deimos', 'Ío', 'Europa', 'Titán'], 'Son satélites naturales.'],
  [['Hidrógeno', 'Helio', 'Litio', 'Berilio', 'Boro'], 'Son los primeros cinco elementos por número atómico.'],
  [['Segundo', 'Metro', 'Kilogramo', 'Amperio', 'Kelvin'], 'Son unidades básicas del Sistema Internacional.'],
  [['Kilo', 'Mega', 'Giga', 'Tera', 'Peta'], 'Son prefijos del SI para múltiplos.'],
  [['Micro', 'Nano', 'Pico', 'Femto', 'Atto'], 'Son prefijos del SI para submúltiplos.'],
  [['Iguazú', 'Los Glaciares', 'El Palmar', 'Talampaya', 'Nahuel Huapi'], 'Son parques nacionales argentinos.'],
  [['Aconcagua', 'Ojos del Salado', 'Huascarán', 'Illimani', 'Chimborazo'], 'Son cumbres de los Andes.'],
  [['Quebrada de Humahuaca', 'Cueva de las Manos', 'Los Glaciares', 'Iguazú', 'Misiones Jesuíticas'], 'Son sitios argentinos de Patrimonio Mundial.'],
  [['París', 'Roma', 'Londres', 'Budapest', 'El Cairo'], 'Son capitales atravesadas por ríos.'],
  [['Nilo', 'Amazonas', 'Yangtsé', 'Misisipi', 'Danubio'], 'Son ríos.'],
  [['Pacífico', 'Atlántico', 'Índico', 'Ártico', 'Austral'], 'Son océanos.'],
  [['Argentina', 'Brasil', 'Chile', 'Uruguay', 'Paraguay'], 'Son países de América del Sur.'],
  [['UNESCO', 'FAO', 'OIT', 'OACI', 'OMI'], 'Son organismos especializados de las Naciones Unidas.'],
  [['China', 'Estados Unidos', 'Francia', 'Reino Unido', 'Rusia'], 'Son miembros permanentes del Consejo de Seguridad de la ONU.'],
  [['Armstrong', 'Aldrin', 'Collins', 'Columbia', 'Eagle'], 'Están vinculados con Apollo 11.'],
  [['Mercury', 'Gemini', 'Apollo', 'Skylab', 'Artemis'], 'Son programas espaciales de NASA.'],
  [['Newton', 'Darwin', 'Curie', 'Mendel', 'Pasteur'], 'Son científicos y científicas asociados a aportes fundamentales.'],
  [['Bell', 'Marconi', 'Nobel', 'Gutenberg', 'Fleming'], 'Son inventores o descubridores vinculados a innovaciones célebres.'],
  [['Don Quijote', 'Frankenstein', 'Orgullo y prejuicio', 'Ficciones', 'Cien años de soledad'], 'Son obras literarias célebres.'],
  [['Guernica', 'Las meninas', 'El grito', 'La noche estrellada', 'La persistencia de la memoria'], 'Son pinturas célebres.'],
  [['Vivaldi', 'Mozart', 'Chaikovski', 'Bizet', 'Ravel'], 'Son compositores de música clásica.'],
  [['Corazón', 'Pulmón', 'Riñón', 'Estómago', 'Cerebro'], 'Son órganos del cuerpo humano.'],
  [['Ballena', 'Murciélago', 'Delfín', 'Caballo', 'Humano'], 'Son mamíferos.'],
  [['Rana', 'Salamandra', 'Sapo', 'Tritón', 'Ajolote'], 'Son anfibios.'],
  [['Básquet', 'Vóley', 'Handball', 'Fútbol', 'Hockey sobre césped'], 'Son deportes de equipo.'],
  [['Yen', 'Won', 'Rupia', 'Corona', 'Peso'], 'Son nombres de monedas.'],
  [['Torre Eiffel', 'Coliseo', 'Cristo Redentor', 'Ópera de Sídney', 'Estatua de la Libertad'], 'Son monumentos o edificios emblemáticos.'],
  [['Octubre', 'Noviembre', 'Diciembre', 'Enero', 'Febrero'], 'Son cinco meses consecutivos del calendario.'],
  [['Sócrates', 'Platón', 'Aristóteles', 'Descartes', 'Kant'], 'Son filósofos.'],
].map(([clues, solution], index) => ({ category: 'common', id: `common-original-${index + 1}`, clues, solution })) as CommonCard[]

const additionalApproximationCards: ApproximationCard[] = [
  ['¿Cuántos kilómetros mide el diámetro ecuatorial de la Tierra?', '12.756 km', 'km', 12756],
  ['¿Cuántos kilómetros mide el diámetro ecuatorial de Júpiter?', '142.984 km', 'km', 142984],
  ['¿Cuántos kilómetros mide el diámetro ecuatorial de Marte?', '6.792 km', 'km', 6792],
  ['¿Cuántos días terrestres dura aproximadamente un año en Mercurio?', '88 días', 'días', 88],
  ['¿Cuántos días terrestres dura aproximadamente un año en Marte?', '687 días', 'días', 687],
  ['¿Cuántos kilómetros hay, en promedio, entre el Sol y la Tierra?', '149.600.000 km', 'km', 149600000],
  ['¿Cuántos kilómetros mide aproximadamente el radio medio de la Luna?', '1.737 km', 'km', 1737],
  ['¿Cuántos metros mide aproximadamente el monte Everest sobre el nivel del mar?', '8.849 m', 'metros', 8849],
  ['¿Cuántos metros tiene la profundidad máxima conocida del océano?', '10.935 m', 'metros', 10935],
  ['¿Cuántos kilómetros cuadrados ocupa aproximadamente la superficie de Argentina?', '2.780.400 km²', 'km²', 2780400],
  ['¿Cuántos kilómetros cuadrados ocupa aproximadamente la superficie de Brasil?', '8.515.767 km²', 'km²', 8515767],
  ['¿Cuántos kilómetros mide aproximadamente el río Paraná?', '4.880 km', 'km', 4880],
  ['¿Cuántos kilómetros mide aproximadamente la Ruta Nacional 40?', '5.194 km', 'km', 5194],
  ['¿Cuántos metros de altura tiene aproximadamente el Aconcagua?', '6.961 m', 'metros', 6961],
  ['¿Cuántos kilómetros cuadrados tiene aproximadamente el Parque Nacional Los Glaciares?', '7.269 km²', 'km²', 7269],
  ['¿Cuántos kilómetros cuadrados tiene aproximadamente el Parque Nacional Iguazú argentino?', '677 km²', 'km²', 677],
  ['¿En qué año se fundó la Organización de las Naciones Unidas?', '1945', 'año', 1945],
  ['¿Cuántos Estados miembros tiene la ONU?', '193', 'Estados', 193],
  ['¿Cuántos miembros tiene el Consejo de Seguridad de la ONU?', '15', 'miembros', 15],
  ['¿Cuántos kilómetros cuadrados protege aproximadamente el Patrimonio Mundial natural?', '3.500.000 km²', 'km²', 3500000],
  ['¿Cuántos minutos tarda aproximadamente la luz del Sol en llegar a la Tierra?', '8 minutos', 'minutos', 8],
  ['¿Cuántos kilómetros por segundo viaja aproximadamente la luz en el vacío?', '299.792 km/s', 'km/s', 299792],
  ['¿Cuántos segundos dura exactamente un día común?', '86.400 segundos', 'segundos', 86400],
  ['¿Cuántos metros hay exactamente en un kilómetro?', '1.000 m', 'metros', 1000],
  ['¿Cuántos metros cuadrados hay exactamente en una hectárea?', '10.000 m²', 'm²', 10000],
  ['¿Cuántos gramos hay exactamente en un kilogramo?', '1.000 g', 'gramos', 1000],
  ['¿Cuántos metros mide aproximadamente la Estatua de la Libertad desde el suelo hasta la antorcha?', '93 m', 'metros', 93],
  ['¿Cuántos años tiene aproximadamente la Tierra?', '4.540.000.000 años', 'años', 4540000000],
  ['¿Cuántos planetas tiene el Sistema Solar?', '8 planetas', 'planetas', 8],
  ['¿Cuántos elementos químicos reconocidos tiene actualmente la tabla periódica?', '118 elementos', 'elementos', 118],
].map(([prompt, display, unit, value], index) => ({ category: 'approximation', id: `approximation-original-${index + 1}`, prompt, solution: { display, unit, value } })) as ApproximationCard[]

export const cardDeck: Record<CardCategory, QuestionCard[]> = {
  sequence: [
    ...additionalSequenceCards,
    {
      category: 'sequence',
      id: 'sequence-053',
      instruction: 'Ordene de menor a mayor los cinturones de karate según su rango:',
      items: ['Azul', 'Marrón', 'Naranja', 'Verde', 'Amarillo'],
      correctOrder: ['Amarillo', 'Naranja', 'Verde', 'Azul', 'Marrón'],
    },
    {
      category: 'sequence',
      id: 'sequence-050',
      instruction: 'Ordene de menor a mayor las manos de póker según su valor:',
      items: ['Full', 'Escalera real', 'Pierna', 'Escalera', 'Póker'],
      correctOrder: ['Pierna', 'Escalera', 'Full', 'Póker', 'Escalera real'],
    },
    {
      category: 'sequence',
      id: 'sequence-046',
      instruction: 'Ordene cronológicamente los libros de Tolkien según su publicación:',
      items: ['Las dos torres', 'La comunidad del anillo', 'El regreso del rey', 'El hobbit', 'El Silmarillion'],
      correctOrder: ['El hobbit', 'La comunidad del anillo', 'Las dos torres', 'El regreso del rey', 'El Silmarillion'],
    },
    {
      category: 'sequence',
      id: 'sequence-039',
      instruction: 'Ordene de mayor a menor los títulos nobiliarios según su jerarquía:',
      items: ['Duque', 'Rey', 'Barón', 'Conde', 'Príncipe'],
      correctOrder: ['Rey', 'Príncipe', 'Duque', 'Conde', 'Barón'],
    },
    {
      category: 'sequence',
      id: 'sequence-081',
      instruction: 'Ordene cronológicamente las guerras:',
      items: ['Guerra de Crimea', 'Segunda Guerra Mundial', 'Guerra de los Treinta Años', 'Guerra del Pacífico o del Salitre', 'Guerra del Golfo'],
      correctOrder: ['Guerra de los Treinta Años', 'Guerra de Crimea', 'Guerra del Pacífico o del Salitre', 'Segunda Guerra Mundial', 'Guerra del Golfo'],
    },
    {
      category: 'sequence',
      id: 'sequence-085',
      instruction: 'Ordene de mayor a menor los animales según su período de gestación:',
      items: ['Caballo', 'Gato', 'Oveja', 'Cerdo', 'Conejo'],
      correctOrder: ['Caballo', 'Oveja', 'Cerdo', 'Gato', 'Conejo'],
    },
    {
      category: 'sequence',
      id: 'sequence-073',
      instruction: 'Ordene de menor a mayor las bandas por cantidad de integrantes:',
      items: ['Aerosmith', 'The Carpenters', 'Dave Matthews Band', 'Queen', 'The Police'],
      correctOrder: ['The Carpenters', 'The Police', 'Queen', 'Aerosmith', 'Dave Matthews Band'],
    },
    {
      category: 'sequence',
      id: 'sequence-038',
      instruction: 'Ordene cronológicamente las series según la emisión de su primer capítulo:',
      items: ['Gossip Girl', 'Ozark', "Grey's Anatomy", 'Friends', 'Familia Ingalls'],
      correctOrder: ['Familia Ingalls', 'Friends', "Grey's Anatomy", 'Gossip Girl', 'Ozark'],
    },
    {
      category: 'sequence',
      id: 'sequence-070',
      instruction: 'Ordene de mayor a menor los animales según su peso promedio:',
      items: ['Elefante', 'Hipopótamo', 'Jirafa', 'León', 'Vaca'],
      correctOrder: ['Elefante', 'Hipopótamo', 'Jirafa', 'Vaca', 'León'],
    },
    {
      category: 'sequence',
      id: 'sequence-164',
      instruction: 'Ordene los siguientes servicios según el año de lanzamiento en Argentina:',
      items: ['Netflix', 'Rappi', 'Spotify', 'Uber', 'WhatsApp'],
      correctOrder: ['WhatsApp', 'Netflix', 'Spotify', 'Uber', 'Rappi'],
    },
    {
      category: 'sequence',
      id: 'sequence-242',
      instruction: 'Ordene de menor a mayor por cantidad de partidos jugados en el Barcelona:',
      items: ['Gabriel Milito', 'Javier Mascherano', 'Javier Saviola', 'Juan Román Riquelme', 'Lionel Messi'],
      correctOrder: ['Juan Román Riquelme', 'Gabriel Milito', 'Javier Saviola', 'Javier Mascherano', 'Lionel Messi'],
    },
    {
      category: 'sequence',
      id: 'sequence-241',
      instruction: 'Ordene de mayor a menor por cantidad de campeonatos ganadas por equipos de ese país:',
      items: ['Alemania', 'España', 'Francia', 'Italia', 'Portugal'],
      correctOrder: ['Italia', 'España', 'Alemania', 'Portugal', 'Francia'],
    },
    {
      category: 'sequence',
      id: 'sequence-240',
      instruction: 'Ordene cronológicamente los momentos en la vida de Emanuel Ginóbili:',
      items: ['Gana la Medalla de Oro con la selección', 'Gana su último anillo de la NBA', 'Es padre de mellizos', 'Juega su último partido con la selección', 'Vence a Estados Unidos en el mundial'],
      correctOrder: ['Vence a Estados Unidos en el mundial', 'Gana la Medalla de Oro con la selección', 'Es padre de mellizos', 'Gana su último anillo de la NBA', 'Juega su último partido con la selección'],
    },
    {
      category: 'sequence',
      id: 'sequence-239',
      instruction: 'Ordene los actores según la edad que tenían cuando ganaron su primer Oscar:',
      items: ['Jeff Bridges', 'Jennifer Lawrence', 'Julie Andrews', 'Leonardo DiCaprio', 'Russell Crowe'],
      correctOrder: ['Jennifer Lawrence', 'Julie Andrews', 'Russell Crowe', 'Leonardo DiCaprio', 'Jeff Bridges'],
    },
    {
      category: 'sequence',
      id: 'sequence-238',
      instruction: 'Ordene cronológicamente los actores según su fecha de nacimiento:',
      items: ['Ricardo Darín', 'Federico Luppi', 'Leonardo Sbaraglia', 'Luis Brandoni', 'Nicolás Vázquez'],
      correctOrder: ['Federico Luppi', 'Luis Brandoni', 'Ricardo Darín', 'Leonardo Sbaraglia', 'Nicolás Vázquez'],
    },
    {
      category: 'sequence',
      id: 'sequence-174',
      instruction: 'Ordene cronológicamente los programas de Santiago del Moro por primera emisión:',
      items: ['¿Quién quiere ser millonario?', 'Intratables', 'Flow', 'MasterChef Celebrity Argentina', 'Infama'],
      correctOrder: ['Flow', 'Infama', 'Intratables', '¿Quién quiere ser millonario?', 'MasterChef Celebrity Argentina'],
    },
  ],
  association: [
    ...additionalAssociationCards,
    {
      category: 'association',
      id: 'association-048',
      instruction: 'Asocie país actual con país del pasado:',
      leftItems: ['Alemania', 'Etiopía', 'Rep. Dem. del Congo', 'Sri Lanka', 'Tailandia'],
      rightItems: ['Prusia', 'Abisinia', 'Ceilán', 'Siam', 'Zaire'],
      pairs: [
        { left: 'Alemania', right: 'Prusia' },
        { left: 'Etiopía', right: 'Abisinia' },
        { left: 'Rep. Dem. del Congo', right: 'Zaire' },
        { left: 'Sri Lanka', right: 'Ceilán' },
        { left: 'Tailandia', right: 'Siam' },
      ],
    },
    {
      category: 'association',
      id: 'association-050',
      instruction: 'Asocie político con asesino:',
      leftItems: ['Trotsky', 'JFK', 'Gandhi', 'Marat', 'Lincoln'],
      rightItems: ['John W. Booth', 'Carlota Corday', 'Ramón Mercader', 'Nathuram Godse', 'Harvey Oswald'],
      pairs: [
        { left: 'Trotsky', right: 'Ramón Mercader' },
        { left: 'JFK', right: 'Harvey Oswald' },
        { left: 'Gandhi', right: 'Nathuram Godse' },
        { left: 'Marat', right: 'Carlota Corday' },
        { left: 'Lincoln', right: 'John W. Booth' },
      ],
    },
    {
      category: 'association',
      id: 'association-057',
      instruction: 'Asocie iglesia con ciudad:',
      leftItems: ['Basílica de San Marcos', 'Sagrada Familia', 'Mezquita Azul', 'Abadía de Westminster', 'Santuario Al Askari'],
      rightItems: ['Barcelona', 'Samarra', 'Estambul', 'Londres', 'Venecia'],
      pairs: [
        { left: 'Basílica de San Marcos', right: 'Venecia' },
        { left: 'Sagrada Familia', right: 'Barcelona' },
        { left: 'Mezquita Azul', right: 'Estambul' },
        { left: 'Abadía de Westminster', right: 'Londres' },
        { left: 'Santuario Al Askari', right: 'Samarra' },
      ],
    },
    {
      category: 'association',
      id: 'association-052',
      instruction: 'Asocie ciudad con museo:',
      leftItems: ['San Petersburgo', 'Ámsterdam', 'París', 'Nueva York', 'Berlín'],
      rightItems: ['Hermitage', 'Museo de Pérgamo', 'Rijksmuseum', 'Louvre', 'Metropolitan'],
      pairs: [
        { left: 'San Petersburgo', right: 'Hermitage' },
        { left: 'Ámsterdam', right: 'Rijksmuseum' },
        { left: 'París', right: 'Louvre' },
        { left: 'Nueva York', right: 'Metropolitan' },
        { left: 'Berlín', right: 'Museo de Pérgamo' },
      ],
    },
    {
      category: 'association',
      id: 'association-035',
      instruction: 'Asocie religión con libro sagrado:',
      leftItems: ['Cristianismo', 'Judaísmo', 'Islamismo', 'Budismo', 'Confucianismo'],
      rightItems: ['Tantra', 'Corán', 'Biblia', 'Las Analectas', 'Torá'],
      pairs: [
        { left: 'Cristianismo', right: 'Biblia' },
        { left: 'Judaísmo', right: 'Torá' },
        { left: 'Islamismo', right: 'Corán' },
        { left: 'Budismo', right: 'Tantra' },
        { left: 'Confucianismo', right: 'Las Analectas' },
      ],
    },
    {
      category: 'association',
      id: 'association-029',
      instruction: 'Asocie deportista con deporte:',
      leftItems: ['Usain Bolt', 'Manny Pacquiao', 'Michael Phelps', 'Vijay Singh', 'Glenn McGrath'],
      rightItems: ['Atletismo', 'Boxeo', 'Críquet', 'Golf', 'Natación'],
      pairs: [
        { left: 'Usain Bolt', right: 'Atletismo' },
        { left: 'Manny Pacquiao', right: 'Boxeo' },
        { left: 'Michael Phelps', right: 'Natación' },
        { left: 'Vijay Singh', right: 'Golf' },
        { left: 'Glenn McGrath', right: 'Críquet' },
      ],
    },
    {
      category: 'association',
      id: 'association-049',
      instruction: 'Asocie maravilla natural con país:',
      leftItems: ['Montaña de la Mesa', 'Bahía de Ha-Long', 'Isla Jeju', 'Parque de Komodo', 'Cataratas del Iguazú'],
      rightItems: ['Argentina', 'Corea del Sur', 'Vietnam', 'Sudáfrica', 'Indonesia'],
      pairs: [
        { left: 'Montaña de la Mesa', right: 'Sudáfrica' },
        { left: 'Bahía de Ha-Long', right: 'Vietnam' },
        { left: 'Isla Jeju', right: 'Corea del Sur' },
        { left: 'Parque de Komodo', right: 'Indonesia' },
        { left: 'Cataratas del Iguazú', right: 'Argentina' },
      ],
    },
    {
      category: 'association',
      id: 'association-056',
      instruction: 'Asocie río con país:',
      leftItems: ['Sena', 'Támesis', 'Volga', 'Ebro', 'San Francisco'],
      rightItems: ['Inglaterra', 'Francia', 'Rusia', 'Brasil', 'España'],
      pairs: [
        { left: 'Sena', right: 'Francia' },
        { left: 'Támesis', right: 'Inglaterra' },
        { left: 'Volga', right: 'Rusia' },
        { left: 'Ebro', right: 'España' },
        { left: 'San Francisco', right: 'Brasil' },
      ],
    },
    {
      category: 'association',
      id: 'association-045',
      instruction: 'Asocie país con marca de ropa:',
      leftItems: ['Japón', 'España', 'Brasil', 'Suecia', 'Reino Unido'],
      rightItems: ['H&M', 'Pepe Jeans', 'Mango', 'Uniqlo', 'Havaianas'],
      pairs: [
        { left: 'Japón', right: 'Uniqlo' },
        { left: 'España', right: 'Mango' },
        { left: 'Brasil', right: 'Havaianas' },
        { left: 'Suecia', right: 'H&M' },
        { left: 'Reino Unido', right: 'Pepe Jeans' },
      ],
    },
    {
      category: 'association',
      id: 'association-032',
      instruction: 'Asocie familia con novela:',
      leftItems: ['Bennet', 'Buendía', 'Rostov', 'Trueba', 'Vidal Olmos'],
      rightItems: ['Cien años de soledad', 'La casa de los espíritus', 'La guerra y la paz', 'Orgullo y prejuicio', 'Sobre héroes y tumbas'],
      pairs: [
        { left: 'Bennet', right: 'Orgullo y prejuicio' },
        { left: 'Buendía', right: 'Cien años de soledad' },
        { left: 'Rostov', right: 'La guerra y la paz' },
        { left: 'Trueba', right: 'La casa de los espíritus' },
        { left: 'Vidal Olmos', right: 'Sobre héroes y tumbas' },
      ],
    },
    {
      category: 'association',
      id: 'association-241',
      instruction: 'Asocie arquero con selección:',
      leftItems: ['Fernando Muslera', 'Jorge Campos', 'José Luis Chilavert', 'Keylor Navas', 'René Higuita'],
      rightItems: ['Costa Rica', 'Colombia', 'México', 'Paraguay', 'Uruguay'],
      pairs: [
        { left: 'Fernando Muslera', right: 'Uruguay' },
        { left: 'Jorge Campos', right: 'México' },
        { left: 'José Luis Chilavert', right: 'Paraguay' },
        { left: 'Keylor Navas', right: 'Costa Rica' },
        { left: 'René Higuita', right: 'Colombia' },
      ],
    },
    {
      category: 'association',
      id: 'association-240',
      instruction: 'Asocie perro con raza:',
      leftItems: ['Huesos (Los Simpsons)', 'Milo (La máscara)', 'Milú (Tintín)', 'Odie (Garfield)', 'Dama (... y el vagabundo)'],
      rightItems: ['Beagle', 'Cocker Spaniel', 'Fox terrier', 'Galgo', 'Jack Russell'],
      pairs: [
        { left: 'Huesos (Los Simpsons)', right: 'Beagle' },
        { left: 'Milo (La máscara)', right: 'Jack Russell' },
        { left: 'Milú (Tintín)', right: 'Fox terrier' },
        { left: 'Odie (Garfield)', right: 'Galgo' },
        { left: 'Dama (... y el vagabundo)', right: 'Cocker Spaniel' },
      ],
    },
    {
      category: 'association',
      id: 'association-239',
      instruction: 'Asocie animal con clase:',
      leftItems: ['Murciélago', 'Pingüino', 'Rana', 'Tiburón', 'Tortuga'],
      rightItems: ['Anfibio', 'Ave', 'Mamífero', 'Pez', 'Reptil'],
      pairs: [
        { left: 'Murciélago', right: 'Mamífero' },
        { left: 'Pingüino', right: 'Ave' },
        { left: 'Rana', right: 'Anfibio' },
        { left: 'Tiburón', right: 'Pez' },
        { left: 'Tortuga', right: 'Reptil' },
      ],
    },
    {
      category: 'association',
      id: 'association-238',
      instruction: 'Asocie provincia con bono emitido previo a la crisis de 2001:',
      leftItems: ['Buenos Aires', 'Córdoba', 'Corrientes', 'Chaco', 'San Juan'],
      rightItems: ['Huarpe', 'Lecor', 'Patacón', 'Quebracho', 'Cecacor'],
      pairs: [
        { left: 'Buenos Aires', right: 'Patacón' },
        { left: 'Córdoba', right: 'Lecor' },
        { left: 'Corrientes', right: 'Cecacor' },
        { left: 'Chaco', right: 'Quebracho' },
        { left: 'San Juan', right: 'Huarpe' },
      ],
    },
    {
      category: 'association',
      id: 'association-237',
      instruction: 'Asocie perro y programa de televisión:',
      leftItems: ['Brian', 'Fatiga', 'Ayudante de Santa', 'Murray', 'Tronco'],
      rightItems: ['Los Simpsons', 'Brigada Cola', 'Casados con hijos', 'Mad About You', 'Padre de Familia'],
      pairs: [
        { left: 'Brian', right: 'Padre de Familia' },
        { left: 'Fatiga', right: 'Casados con hijos' },
        { left: 'Ayudante de Santa', right: 'Los Simpsons' },
        { left: 'Murray', right: 'Mad About You' },
        { left: 'Tronco', right: 'Brigada Cola' },
      ],
    },
    {
      category: 'association',
      id: 'association-168',
      instruction: 'Asocie compositor con obra musical:',
      leftItems: ['Chaikovski', 'Schubert', 'Verdi', 'Puccini', 'Mozart'],
      rightItems: ['Ave María', 'La traviata', 'La bohème', 'El lago de los cisnes', 'La flauta mágica'],
      pairs: [
        { left: 'Chaikovski', right: 'El lago de los cisnes' },
        { left: 'Schubert', right: 'Ave María' },
        { left: 'Verdi', right: 'La traviata' },
        { left: 'Puccini', right: 'La bohème' },
        { left: 'Mozart', right: 'La flauta mágica' },
      ],
    },
  ],
  common: [
    ...additionalCommonCards,
    {
      category: 'common',
      id: 'common-057',
      clues: ['Perazzi', 'Bersa', 'Taurus', 'Heckler & Koch'],
      solution: 'Son marcas de armas.',
    },
    {
      category: 'common',
      id: 'common-064',
      clues: ['Laertes', 'Mercucio', 'Romeo', 'Shylock', 'Ariel'],
      solution: 'Son personajes creados por Shakespeare.',
    },
    {
      category: 'common',
      id: 'common-037',
      clues: ['Anna Scott', 'Julianne Potter', 'Maggie Carpenter', 'Katherine Watson', 'Tess Ocean'],
      solution: 'Fueron papeles interpretados por Julia Roberts.',
    },
    {
      category: 'common',
      id: 'common-054',
      clues: ['Jim Morrison', 'Janis Joplin', 'Jean-Michel Basquiat', 'Kurt Cobain', 'Amy Winehouse'],
      solution: 'Murieron a los 27 años.',
    },
    {
      category: 'common',
      id: 'common-056',
      clues: ['Reino Unido', 'Francia', 'España', 'Argelia', 'Mali'],
      solution: 'Son países atravesados por el Meridiano de Greenwich.',
    },
    {
      category: 'common',
      id: 'common-069',
      clues: ['El gran dictador', 'Tiempos modernos', 'El pibe', 'El circo', 'El inmigrante'],
      solution: 'Son películas de Charlie Chaplin.',
    },
    {
      category: 'common',
      id: 'common-081',
      clues: ['Ramón Gómez Valdés Castillo', 'María Antonieta de las Nieves', 'Carlos Villagrán Eslava', 'Rubén Aguirre Fernández Abad', 'Édgar Vivar'],
      solution: 'Son actores de la serie El Chavo del 8.',
    },
    {
      category: 'common',
      id: 'common-039',
      clues: ['Barack Obama', 'Jimmy Carter', 'Nelson Mandela', 'Mijaíl Gorbachov', 'Madre Teresa'],
      solution: 'Recibieron el Premio Nobel de la Paz.',
    },
    {
      category: 'common',
      id: 'common-069-tribes',
      clues: ['Sioux', 'Comanches', 'Mohicanos', 'Cherokee', 'Apaches'],
      solution: 'Son tribus indígenas norteamericanas.',
    },
    {
      category: 'common',
      id: 'common-038',
      clues: ['Seda', 'Manteca', 'Aluminio', 'Vegetal', 'Romaní'],
      solution: 'Son tipos de papel.',
    },
    {
      category: 'common',
      id: 'common-237',
      clues: ['La mala educación', 'Todo sobre mi madre', 'Tacones lejanos', 'La ley del deseo', 'Matador'],
      solution: 'Son películas dirigidas por Pedro Almodóvar.',
    },
    {
      category: 'common',
      id: 'common-242',
      clues: ['Rubén Rada', 'Hugo Ibarra', 'Alberto Olmedo', 'Horacio Fontova', 'Oscar González Oro'],
      solution: 'Su apodo es “Negro”.',
    },
    {
      category: 'common',
      id: 'common-240',
      clues: ['Fukushima I', 'Chernobyl', 'Atucha I', 'Three Mile Island', 'Angra I'],
      solution: 'Son plantas nucleares.',
    },
    {
      category: 'common',
      id: 'common-239',
      clues: ['Copa Intercontinental 2007', 'Copa Libertadores 2007', 'Apertura 2011', 'Copa Argentina 2021', 'Liga Profesional 2022'],
      solution: 'Son torneos de fútbol donde Boca Juniors salió campeón.',
    },
    {
      category: 'common',
      id: 'common-238',
      clues: ["Francia '38", "Brasil '50", "Suiza '54", "México '70"],
      solution: 'La selección argentina no participó.',
    },
    {
      category: 'common',
      id: 'common-174',
      clues: ['Bolívar', 'Chimborazo', 'Galán', 'Tronador', 'Fitz Roy'],
      solution: 'Son picos de la cordillera de los Andes.',
    },
  ],
  approximation: [
    ...additionalApproximationCards,
    {
      category: 'approximation',
      id: 'approximation-053',
      prompt: '¿Cuántos días estuvieron atrapados en la mina los 33 mineros de Chile tras el derrumbe hasta ser rescatados?',
      solution: { display: '69 días', unit: 'días', value: 69 },
    },
    {
      category: 'approximation',
      id: 'approximation-029',
      prompt: '¿Cuál es la distancia entre París y Nueva York?',
      solution: { display: '5.836,77 km', unit: 'km', value: 5836.77 },
    },
    {
      category: 'approximation',
      id: 'approximation-058',
      prompt: '¿En qué año se montó el primer cinturón de seguridad como equipamiento estándar de un automóvil de producción masiva?',
      solution: { display: '1959', unit: 'año', value: 1959 },
    },
    {
      category: 'approximation',
      id: 'approximation-059',
      prompt: '¿Cuántos goles convirtió la selección argentina en Copas mundiales hasta 2022? (incluido el Mundial de Qatar)',
      solution: { display: '152 goles', unit: 'goles', value: 152 },
    },
    {
      category: 'approximation',
      id: 'approximation-031',
      prompt: '¿Cuál es la distancia media entre el centro de la Tierra y la Luna?',
      solution: { display: '384.403 km', unit: 'km', value: 384403 },
    },
    {
      category: 'approximation',
      id: 'approximation-050',
      prompt: '¿Cuántas lentejas hay en un paquete de 1 kilo?',
      solution: { display: '22.300 lentejas', unit: 'lentejas', value: 22300 },
    },
    {
      category: 'approximation',
      id: 'approximation-030',
      prompt: '¿Cuántas horas tardó la misión Apolo XI desde su lanzamiento hasta su amerizaje?',
      solution: { display: '102 horas y 47 minutos', unit: 'minutos', value: 6167 },
    },
    {
      category: 'approximation',
      id: 'approximation-028',
      prompt: '¿En qué fecha fue presentada la primera versión de Windows (1.0)?',
      solution: { display: 'El 10 de noviembre de 1983', unit: 'año', value: 1983 },
    },
    {
      category: 'approximation',
      id: 'approximation-042',
      prompt: '¿Cuántos años vivió Leonardo da Vinci?',
      solution: { display: '67 años', unit: 'años', value: 67 },
    },
    {
      category: 'approximation',
      id: 'approximation-002',
      prompt: '¿Cuántos visitantes tuvo el Museo del Louvre en el año 2019?',
      solution: { display: '9.600.000 visitantes', unit: 'visitantes', value: 9600000 },
    },
    {
      category: 'approximation',
      id: 'approximation-241',
      prompt: '¿En qué fecha fue puesto en órbita el primer satélite argentino Lusat 1?',
      solution: { display: '22 de enero de 1990', unit: 'año', value: 1990 },
    },
    {
      category: 'approximation',
      id: 'approximation-242',
      prompt: '¿Cuántos casos resolvieron en pantalla “Los Simuladores”?',
      solution: { display: '35 casos', unit: 'casos', value: 35 },
    },
    {
      category: 'approximation',
      id: 'approximation-240',
      prompt: '¿Cuál es la capacidad del estadio Club Atlético River Plate?',
      solution: { display: '72.054 espectadores', unit: 'espectadores', value: 72054 },
    },
    {
      category: 'approximation',
      id: 'approximation-239',
      prompt: '¿Cuántos faros hay en la República Argentina?',
      solution: { display: '62 faros', unit: 'faros', value: 62 },
    },
    {
      category: 'approximation',
      id: 'approximation-238',
      prompt: '¿Cuántas palabras tiene el Preámbulo de la Constitución Nacional Argentina?',
      solution: { display: '100 palabras', unit: 'palabras', value: 100 },
    },
    {
      category: 'approximation',
      id: 'approximation-160',
      prompt: '¿Cuántos metros tiene el perímetro de la Quinta Presidencial en Olivos?',
      solution: { display: '2.601 metros', unit: 'metros', value: 2601 },
    },
  ],
}
